src/Entity/Band.php
<?php

namespace App\Entity;

use Webmozart\Assert\Assert;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\BandRepository;
use Symfony\Component\Validator\Constraints\NotBlank;

/**
 * @ORM\Entity(repositoryClass=BandRepository::class)
 */
class Band
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $mainPicture;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\ManyToOne(targetEntity=Style::class, inversedBy="bands")
     * @ORM\JoinColumn(nullable=false)
     */
    private $style;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_featured;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getMainPicture(): ?string
    {
        return $this->mainPicture;
    }

    public function setMainPicture(string $mainPicture): self
    {
        $this->mainPicture = $mainPicture;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getStyle(): ?style
    {
        return $this->style;
    }

    public function setStyle(?style $style): self
    {
        $this->style = $style;

        return $this;
    }

    public function getIsFeatured(): ?bool
    {
        return $this->is_featured;
    }

    public function setIsFeatured(bool $is_featured): self
    {
        $this->is_featured = $is_featured;

        return $this;
    }
}

templates/_partials/_createBand.html.twig
{{ form_start(formCreateBand) }}

{{ form_errors(formCreateBand) }}
<h1 class="h1">Création d'un Groupe | Artiste</h1>
<div class="row">

    <div class="col">
        {{ form_row(formCreateBand.name) }}
        {{ form_row(formCreateBand.mainPicture) }}
    </div>
    <div class="col">
        {{ form_row(formCreateBand.description) }}
    </div>

</div>

<div class="row">
    {{ form_row(formCreateBand.style)}}
    {{ form_row(formCreateBand.isFeatured)}}
</div>

<button type="submit" class="btn btn-success validate">
    <i class="far fa-save"></i> 
    Enregistrer
</button>

{{ form_end(formCreateBand) }}

{% block form_row %}
    
    {# {{ form_label(form) }}
    {{ form_widget(form) }}
    {{ form_help(form) }}
    {{ form_errors(form) }} #}
    
{% endblock %}

templates/_partials/_footer.html.twig
    <footer class="footer mt-auto py-3 bg-light">
        <section class="mb-4 px-4">
            <a href="" class="" role="button">
                <i class="fab fa-bandcamp"></i>
                Bandcamp
            </a>
            <a href="" class="" role="button">
                <i class="fab fa-facebook"></i>
                Faceboook
            </a>
            <a href="" class="" role="button">
                <i class="fas fa-at"></i>
                Contact
            </a>
        </section>
        <section class="link">
            <div class="row">
                <!--Grid column-->
                <div class="col-lg-3 col-md-6 mb-4 mb-md-0 mx-2">
                    <h5 class="text-uppercase">Styles :</h5>

                    <ul class="list-unstyled mb-0">
                        {% for style in styles %}
                        <li>
                            <img src="{{ asset('build/images/vinyl.svg') }}" class="vinyl" alt="icone styles" >
                            <a href="#!" class="">{{style.name}}</a>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
                <!--Grid column-->
                <!--Grid column-->
                <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
                    <h5 class="text-uppercase">Connexions :</h5>
                    {% if app.user %}
                        <li>
                            <a href="{{path('security_logout')}}" class="btn btn-danger"><i class="fas fa-sign-out-alt"></i> Déconnexion</a>
                        </li>
                    {% else %}
                        <li><a href="{{path('security_login')}}" class="btn"><i class="fas fa-sign-in-alt"></i> Connexion</a></li>
                        <li><a href="" class="btn"><i class="fas fa-user-plus"></i> Inscription</a></li>
                    {% endif %}

                    <ul class="list-unstyled mb-0">
                        <ul>
                            <li>
                                <a href="" class="" role="button">
                                    <i class="fas fa-at"></i>
                                    Contact
                                </a>
                            </li>
                        </ul>
                    </ul>
                </div>
                <!--Grid column-->
            </div>
        </section>
    </footer>
</body>
</html>

templates/_partials/_homeAdmin.html.twig
<img src="{{ asset('build/images/header-offoron.png') }}" class="header-admin" alt="header de la page administration">
{# le workflow #}
<h2 class="display-6 text-muted">workflow:</h2>
<nav style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='white'/%3E%3C/svg%3E&#34;);" aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item badge bg-green">Créer Style</li>
        <li class="breadcrumb-item badge bg-green">Créer Groupe</li>
        <li class="breadcrumb-item badge bg-green">Créer Membre</li>
        <li class="breadcrumb-item badge bg-green">Créer Album</li>
    </ol>
</nav>

templates/_partials/_navbar.html.twig
{# <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#"> 
      <img src="{{ asset('build/images/vinyl.svg') }}" class="vinyl" alt="icone styles" >
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="line1"></span>
      <span class="line2"></span>
      <span class="line3"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-link active" aria-current="page" href="#">Home</a>
        {% for style in styleRepository.findAll() %}
        <a href="" class="nav-link">{{style.name}}</a>
        {% endfor %}
      </div>
      <div class="navbar-nav">
        <a href="" class="nav-link">Inscription</a>
        <a href="" class="btn btn-success">Login</a>
        <a href="" class="btn btn-danger">Logout</a>
      </div>
    </div>
  </div>
</nav> #}
<nav>
  <div class="logo">
      <a class="navbar-brand" href="#"> 
        <img src="{{ asset('build/images/vinyl.svg') }}" class="vinyl" alt="icone styles" >
      </a>
  </div>
  
  {% if app.user %}
    <li style="list-style: none;">
        <a href="{{path('security_logout')}}" class="btn btn-danger"><i class="fas fa-sign-out-alt"></i> Déconnexion</a>
    </li>
  {% endif %}
  <ul class="nav-links">
    {% for style in styleRepository.findAll() %}
      <li><a href="" class="nav-link">{{style.name}}</a></li>
    {% endfor %}
  </ul>
  <div class="burger">
    <div class="line1"></div>
    <div class="line2"></div>
    <div class="line3"></div>
  </div>
</nav>